name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
    - name: Format
      run: cd hello-world && cargo fmt -- --check
    - name: Check
      run: cd hello-world && cargo check
    - name: Clippy
      run: cd hello-world && cargo check
    - name: Test
      run: cd hello-world && cargo test --verbose
    - name: Audit
      run: cd hello-world && cargo check
