name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cd hello-world && cargo fmt -- --check
    - name: Check
      run: cd hello-world && cargo check
    - name: Run tests
      run: cd hello-world && cargo test --verbose
